### PR TITLE
Update libtorrent to 1.2.18

### PR DESCRIPTION
**Pull request by Chocobo1**

### CODE REVIEW

**Comment by Chocobo1** [comment]
@TingPing 
Sorry to ping you. I don't know how to resolve the build error. It seems to be related to ` --own-name=org.kde.StatusNotifierItem-2-2`, yet I'm not sure what is going on...

```
flatpak run --command=flatpak-builder-lint org.flatpak.Builder --exceptions org.qbittorrent.qBittorrent.yaml
 in dir /srv/buildbot/worker/build-x86_64-1/build (timeout 1200 secs)
 watching logfiles {}
 argv: b'flatpak run --command=flatpak-builder-lint org.flatpak.Builder --exceptions org.qbittorrent.qBittorrent.yaml'
 using PTY: False
{
    "errors": [
        "finish-args-broken-kde-tray-permission"
    ],
    "warnings": [
        "finish-args-contains-both-x11-and-wayland"
    ]
}
If you think problems listed above are a false positive, please report it here:
  https://github.com/flathub/flatpak-builder-lint
program finished with exit code 1
elapsedTime=0.562375
```

BTW, where can I look for announcement for such changes? or who can I ping when such difficulties arises in the future?

**Comment by Erick555** [comment]
Use `--own-name=org.kde.*` instead of `--own-name=org.kde.StatusNotifierItem-2-2` and `--socket=fallback-x11` instead of `--socket=x11`.

**Comment by TingPing** [comment]
> Use --own-name=org.kde.* instead of --own-name=org.kde.StatusNotifierItem-2-2

This linter error is wrong.. but I guess so.

**Comment by TingPing** [comment]
https://github.com/flathub/flatpak-builder-lint/issues/66

**Pull request merged**
