### PR TITLE
Update to kde 5.13

### PR DESCRIPTION
**Pull request by Erick555**

### CODE REVIEW

**Comment by Erick555** [comment]
@eszlari please review

**Comment by eszlari** [comment]
Have you tested the app? Please don't change the source URL.

**Comment by Erick555** [comment]
@eszlari why?

**Comment by eszlari** [comment]
Because these are the official tarball, and they also provide the checksum on their site:
https://www.qbittorrent.org/download.php

**Comment by Erick555** [comment]
@eszlari I removed source change and tested downloading torrent file which worked fine.

**Pull request merged**
