### PR TITLE
Bump the runtime to 5.15-22.08

### PR DESCRIPTION
**Pull request by farribeiro**

### CODE REVIEW

**Comment by Chocobo1** [comment]
@farribeiro 
Thank you!

**Comment by konaOnTheHub** [comment]
I noticed with qBittorrent (and other applications as well) as soon as they inhibit the new 5.15-22 runtime the app fails to pick up on my systems dark theme on GNOME and runs with a light theme instead.

**Comment by travier** [comment]
Hey folks, we've published the new Runtime but we're still testing it and we haven't made an announcement yet. Reach out if you encounter issues. Thanks

**Comment by travier** [comment]
As the new KDE 5.15-22.08 Runtime is not yet ready and users are facing issue, I think you should consider reverting this and waiting until we've done more testing: https://github.com/flathub/org.kde.KStyle.Adwaita/issues/12

**Comment by Chocobo1** [comment]
@travier 
Thanks for the info! Aside from that, I've always wonder where should I subscribe to the latest news on the KDE Runtime? I mean where will the announcement be made?

**Comment by travier** [comment]
We will announce it on the Flathub Discourse: https://discourse.flathub.org/c/announcements/6

**Comment by Chocobo1** [comment]
>As the new KDE 5.15-22.08 Runtime is not yet ready and users are facing issue, I think you should consider reverting this and waiting until we've done more testing: https://github.com/flathub/org.kde.KStyle.Adwaita/issues/12

See PR #91.

**Pull request merged**
