### PR TITLE
Update org.kde.Platform to 5.15-21.08

### PR DESCRIPTION
**Pull request by tim77**
Update `org.kde.Platform` to latest runtime based on FD.o 21.08.

### CODE REVIEW

**Comment by tim77** [comment]
bot, build org.qbittorrent.qBittorrent

**Comment by cho2** [comment]
@Chocobo1

**Comment by Chocobo1** [comment]
What is "FD.o 21.08"?
How can I know this is the latest version? I mean where can I track it?

**Comment by tim77** [comment]
@Chocobo1 it's KDE 5.15 but re-based on the Freedesktop 21.08 runtime, see https://invent.kde.org/packaging/flatpak-kde-runtime/-/issues/22.

**Pull request merged**
