### PR TITLE
runtime: update to version 5.15

### PR DESCRIPTION
**Pull request by ElXreno**
* Runtime: Update to version 5.15

### CODE REVIEW

**Comment by Eonfge** [comment]
@TingPing I'm sorry to bother you, but it appears that @eszlari is unavailable to merge these changes. Could these outstanding updates be escalated? Also, who would be best to bother with these kinds of things?

**Comment by TingPing** [comment]
@Eonfge Would you like to become maintainer?

**Comment by ElXreno** [comment]
@TingPing I can support qBittorrent if needed.

**Comment by Eonfge** [comment]
@TingPing I think that @ElXreno would be more suited, since he made the pull requests.

Also, my PC doesn't actually have enough memory to compile qBittorrent, so that's quite an inconvenience to be the daily maintainer

**Pull request merged**
