### PR TITLE
Update libtorrent to 1.2.11

### PR DESCRIPTION
**Pull request by Chocobo1**

### CODE REVIEW

**Comment by eszlari** [comment]
@Chocobo1 Do have commit access?

**Comment by Chocobo1** [comment]
>@Chocobo1 Do you have commit access?

No, I don't.

**Comment by eszlari** [comment]
@barthalion @bilelmoussaoui @nedrichards Could give @Chocobo1 commit access? He is a qBittorrent upstream developer.

**Comment by bilelmoussaoui** [comment]
> @barthalion @bilelmoussaoui @nedrichards Could you give @Chocobo1 commit access? He is a qBittorrent upstream developer.

Done

**Comment by Chocobo1** [comment]
Thank you.
I suppose I can merge this PR myself?

**Comment by eszlari** [comment]
> I suppose I can merge this PR myself?

Sure.

**Pull request merged**
